package common

const (
	// MCONamespace is the namespace where the MCO is running, and where its objects live
	MCONamespace = "openshift-machine-config-operator"

	// GeneratedByControllerVersionAnnotationKey is used to tag the machineconfigs generated by the controller with the version of the controller.
	GeneratedByControllerVersionAnnotationKey = "machineconfiguration.openshift.io/generated-by-controller-version"

	// ReleaseImageVersionAnnotationKey is used to tag the rendered machineconfigs & controller config with the release image version.
	ReleaseImageVersionAnnotationKey = "machineconfiguration.openshift.io/release-image-version"

	// ControllerConfigName is the name of the ControllerConfig object that controllers use
	ControllerConfigName = "machine-config-controller"

	// KernelTypeDefault denominates the default kernel type
	KernelTypeDefault = "default"

	// KernelTypeRealtime denominates the realtime kernel type
	KernelTypeRealtime = "realtime"

	// MasterLabel defines the label associated with master node. The master taint uses the same label as taint's key
	MasterLabel = "node-role.kubernetes.io/master"

	// MCNameSuffixAnnotationKey is used to keep track of the machine config name associated with a CR
	MCNameSuffixAnnotationKey = "machineconfiguration.openshift.io/mc-name-suffix"

	// MaxMCNameSuffix is the maximum value of the name suffix of the machine config associated with kubeletconfig and containerruntime objects
	MaxMCNameSuffix int = 9

	// ClusterFeatureInstanceName is a singleton name for featureGate configuration
	ClusterFeatureInstanceName = "cluster"

	// ExperimentalLayeringPoolLabel is the label that enables the "layered" workflow path for a pool
	ExperimentalLayeringPoolLabel = "machineconfiguration.openshift.io/layered"
	// ExperimentalNewestLayeredImageAnnotationKey is the annotation that signifies the newest image that has been rendered to a machine
	// config pool's imagestream
	ExperimentalNewestLayeredImageAnnotationKey = "machineconfiguration.openshift.io/newestImage"
	// ExperimentalNewestLayeredImageEquivalentConfigAnnotationKey is the annotation that signifies which rendered config
	// the currently rendered image is equivalent to
	ExperimentalNewestLayeredImageEquivalentConfigAnnotationKey = "machineconfiguration.openshift.io/newestImageEquivalentConfig"

	// ImageStreamSuffixRenderedConfig is the suffix for a pool imagestream where the mco also writes its rendered machineconfig
	ImageStreamSuffixRenderedConfig = "-rendered-config"
	// ImageStreamSuffixMcoContent  is the suffix for a pool imagestream where the mco has applied its rendered-config to the base image
	ImageStreamSuffixMcoContent = "-mco-content"
	// ImageStreamSuffixMcoContentCustom is the suffix for a pool imagestream where content has been customized by a user
	ImageStreamSuffixMcoContentCustom = "-mco-content-custom"
	// ImageStreamSuffixMcoContentExternal is the suffix for a pool imagestream  where content comes from outside the cluster
	ImageStreamSuffixMcoContentExternal = "-mco-content-external"
)
