apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: layered
  name: live-apply-file
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,V29vaG9vIGxpdmUgYXBwbHkgd29ya3MhCg==
          path: /etc/machine-config-daemon/no-reboot/containers-gpg.pub
