apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: machine-config-controller-controller-builds-imagestreams
  namespace: {{.TargetNamespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: machine-config-controller
subjects:
- kind: ServiceAccount
  name: machine-config-controller
  namespace: {{.TargetNamespace}}