---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhel-coreos-8-extensions
  namespace: openshift-machine-config-operator
  labels:
    k8s-app: rhel-coreos-8-extensions
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rhel-coreos-8-extensions
  template:
    metadata:
      labels:
        k8s-app: rhel-coreos-8-extensions
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      containers:
      - name: rhel-coreos-8-extensions
        image: {{.ControllerConfig.BaseOperatingSystemExtensionsContainer}}
        args:
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
        env:
          - name: RELEASE_VERSION
            value: "0.0.1-snapshot"
        terminationMessagePolicy: FallbackToLogsOnError
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120

   