apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: machine-config-controller
  namespace: {{.TargetNamespace}}
rules:
- apiGroups: ["build.openshift.io"]
  resources: ["builds","buildconfigs","buildconfigs/instantiate"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreams"]
  verbs: ["get","list","watch","create","update","patch","delete"]
